name: Tag

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

env:
  tag_prefix: "v"

permissions:
  contents: write

jobs:
    create-tag:
        name: "Create Tag"
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        outputs:
            tag: ${{ steps.calculate_tag_version.outputs.version_tag }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Check for Go file changes
          id: check_changes
          run: |
            # Get the commit SHA from the workflow run that triggered this
            COMMIT_SHA="${{ github.event.workflow_run.head_sha }}"

            # Check if any Go files were changed in the last commit
            GO_FILES_CHANGED=$(git diff --name-only $COMMIT_SHA~1 $COMMIT_SHA | grep -E '\.(go|mod|sum)$' || true)

            if [ -n "$GO_FILES_CHANGED" ]; then
              echo "go_files_changed=true" >> $GITHUB_OUTPUT
              echo "Go files changed:"
              echo "$GO_FILES_CHANGED"
            else
              echo "go_files_changed=false" >> $GITHUB_OUTPUT
              echo "No Go files changed, skipping tag creation"
            fi

        - name: SemVer
          if: steps.check_changes.outputs.go_files_changed == 'true'
          uses: paulhatch/semantic-version@v5.4.0
          id: calculate_tag_version
          with:
            tag_prefix: "${{ env.tag_prefix }}"
            major_pattern: "(BREAKING CHANGE|feat!|fix!|refactor!)"
            minor_pattern: "(feat|feature)"
            version_format: "v${major}.${minor}.${patch}"
            bump_each_commit: false
            search_commit_body: true
            debug: true

        - name: Create Tag
          if: steps.check_changes.outputs.go_files_changed == 'true'
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_tag: ${{ steps.calculate_tag_version.outputs.version_tag }}
            tag_prefix: ""
