name: Tag

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

env:
  tag_prefix: "v"

permissions:
  contents: write

jobs:
    prepare-github-release:
        name: "Create Release"
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        outputs:
            version_tag: ${{ steps.calculate_tag_version.outputs.version_tag }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: SemVer
          uses: paulhatch/semantic-version@v5.4.0
          id: calculate_tag_version
          with:
            tag_prefix: "${{ env.tag_prefix }}"
            major_pattern: "(BREAKING CHANGE|feat!|fix!|refactor!)"
            minor_pattern: "(feat|feature)"
            version_format: "v${major}.${minor}.${patch}"
            bump_each_commit: false
            search_commit_body: true
            debug: true

        - name: Bump version
          # https://github.com/mathieudutour/github-tag-action
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            custom_tag: ${{ steps.calculate_tag_version.outputs.version_tag }}
            tag_prefix: ""  # NOBUG: intentionally set empty

        - name: Create Release
          uses: ncipollo/release-action@v1.14.0
          with:
            tag: ${{ steps.calculate_tag_version.outputs.version_tag }}
            name: Release ${{ steps.calculate_tag_version.outputs.version_tag }}
            body: ${{ steps.tag_version.outputs.changelog }}
            generateReleaseNotes: true
